language: python

python:
- '3.6'

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -r test-requirements.txt

before_script:
- python manage.py migrate
- python manage.py collectstatic --noinput

script:
- black --check mysite mercury
- flake8 mysite mercury
- coverage run --source=mysite,mercury --omit="mercury/migrations/*","mysite/wsgi.py" manage.py test

after_script:
- coveralls

notifications:
    slack: gcivil-nyu:ahgpmz0a0XgrrUU3E9kPk9kZ

